<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework></PropertyGroup>
  <PropertyGroup><OutputType>Exe</OutputType><IsPackable>false</IsPackable></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/DevelKit.MessageTemplates/DevelKit.MessageTemplates.csproj" />
    <ProjectReference Include="../../src/DevelKit.MessageTemplates.SqlServer/DevelKit.MessageTemplates.SqlServer.csproj" />
  </ItemGroup>
</Project>